---
name: eliud_core_model
description: Eliud core is the core eliud package. It's a required package for all
  eliud apps. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_core
version: 1.1.5+7
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  another_flushbar: ^1.12.30
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  cloud_functions: ^4.5.3
  collection: ^1.17.2
  crypto: ^3.0.3
  equatable: ^2.0.5
  datetime_picker_formfield_new: ^2.1.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.21.0
  firebase_storage: ^11.4.1
  flutter_bloc: ^8.1.3
  flutter_colorful_tab: ^0.1.0
  flutter_colorpicker: ^1.0.3
  flutter_markdown: ^0.6.18+2
  flutter_signin_button: ^2.0.0
  get_thumbnail_video: ^0.6.1
  google_sign_in: ^6.1.5
  http: ^1.1.0
  image: ^4.1.3
  intl: ^0.18.1
  meta: ^1.9.1
  path: ^1.8.3
  path_provider: ^2.1.1
  pdfx: ^2.5.0
  pointer_interceptor: ^0.9.3+6
  sign_in_with_apple: ^5.0.0
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  uuid: ^4.2.1
  universal_html: ^2.2.4
  flutter:
    sdk: flutter
  eliud_core_main:
    path: ../eliud_core_main
  eliud_core_helpers:
    path: ../eliud_core_helpers
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
